"""create titulos tesouro

Revision ID: 0ec13e7f80cd
Revises: 
Create Date: 2026-05-18 20:40:03.175608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec13e7f80cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulos_tesouro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('vencimento', sa.String(length=20), nullable=False),
    sa.Column('taxa_compra', sa.Float(), nullable=False),
    sa.Column('taxa_venda', sa.Float(), nullable=False),
    sa.Column('preco_compra', sa.Float(), nullable=False),
    sa.Column('preco_minimo', sa.Float(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titulos_tesouro')
    # ### end Alembic commands ###
